### ISSUE TITLE
How to keep ShellCheck happy ?

### ISSUE THREAD

**Issue by ngirard** [agnipau/slap#8]
Running [ShellCheck](https://github.com/koalaman/shellcheck) against a "slapped" script produces one warning per variable ; for instance:
```
)"; [[ -z "${_success}" ]] && exit 1
           ^---------^ SC2154: _success is referenced but not assigned.
```
How could we silent ShellCheck when using Slap ?
The only way I could think of is to add
```sh
# shellcheck disable=SC2154
```
below the shebang ; but doing so will prevent further errors with non-slap variables from being reported.

Any thoughts ?

**Comment by guardam** [comment]
<https://github.com/koalaman/shellcheck/wiki/SC2154#exceptions>

Seems like the viable workarounds are:
- Using `${var:?}`. This means that if `var` is unset or empty, the program will exit with an error code.
- Explicitly declare the variables before or after the `eval`, with `declare var`, or initialize the variables before the eval with `var=""`.
- Initialize if not assigned, for example `${var:=}`.
- Use `shellcheck disable=SC2154` before the problematic line. If you put this directive after the shebang it will be applied to all the file, if you put it just before the line, it will be applied only to that line.

Sadly this problem can't be solved from the "slap side". The only possible workaround I can think of is to export an hash-map instead of multiple variables, in which case you would need only one directive (for the hash-map), and not for its values. This is possible to implement for shells like BASH and ZSH, but some shells don't support this, most notably the POSIX sh standard.

I would like to have the option to export as an hash-map for shells that support hash-maps, so in the future it will be added. For now the user has to choose from one of the four workarounds before-mentioned. I'm going to add a section to the README, thank you.

**Comment by ngirard** [comment]
Thanks for your thoughts !

>     * Use `shellcheck disable=SC2154` before the problematic line. If you put this directive after the shebang it will be applied to all the file, if you put it just before the line, it will be applied only to that line.

Oh, I didn't know that was possible. Putting the directive right after the `slap` invocation seems like a good compromise to me !
